# Generated by Django 5.1.5 on 2025-03-03 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='color',
        ),
        migrations.AddField(
            model_name='mobile',
            name='camera',
            field=models.CharField(default='12MP', max_length=100),
        ),
        migrations.AddField(
            model_name='mobile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mobile',
            name='ram',
            field=models.CharField(default='6GB', max_length=50),
        ),
        migrations.AddField(
            model_name='mobile',
            name='screen_size',
            field=models.CharField(default='6.1 inch', max_length=50),
        ),
        migrations.AddField(
            model_name='mobile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mobiles/'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='storage',
            field=models.CharField(default='128GB', max_length=50),
        ),
    ]
