# Generated by Django 5.1.5 on 2025-03-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_shoes_alter_cartitem_book'),
        ('clothes', '0002_alter_clothes_options_clothes_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='clothes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
