# Generated by Django 5.1.5 on 2025-03-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_clothes_alter_cartitem_quantity'),
        ('mobiles', '0002_alter_mobile_options_remove_mobile_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobiles.mobile'),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_cartitem',
        ),
    ]
