# Generated by Django 5.1.5 on 2025-03-03 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('order', '0002_alter_order_options_alter_order_customer_and_more'),
        ('shoes', '0002_alter_shoes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes.shoes'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.book'),
        ),
    ]
