# Generated by Django 5.1.5 on 2025-03-03 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothes_options_clothes_created_at_and_more'),
        ('order', '0003_orderitem_shoes_alter_orderitem_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='clothes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.clothes'),
        ),
    ]
