# Generated by Django 5.1.5 on 2025-03-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_clothes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('bank', 'Chuyển khoản ngân hàng'), ('credit', 'Thẻ tín dụng')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'Giao hàng tiêu chuẩn (3-5 ngày)'), ('express', 'Giao hàng nhanh (1-2 ngày)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('shipped', 'Đang giao hàng'), ('delivered', 'Đã giao hàng')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_orderitem',
        ),
    ]
