# Generated by Django 5.1.5 on 2025-03-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='shoes/')),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
