# Generated by Django 5.1.5 on 2025-03-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name': 'Shoes', 'verbose_name_plural': 'Shoes'},
        ),
    ]
